liquibase:
  change-log: classpath:db/db.changelog-master.xml
  password: rms
  url: jdbc:h2:mem:rms
  user: rms

---
spring:
  h2:
    console:
      enabled: true
      path: /h2

---
spring:
  datasource:
    url: jdbc:h2:mem:rms;DB_CLOSE_ON_EXIT=FALSE;
    username: rms
    password: rms
    driver-class-name: org.h2.Driver
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: validate

---
spring:
  messages:
    basename: i18n/message_en

---
spring:
  mvc:
    locale: en
